### ISSUE TITLE
Problem with out-of-date devDependency Http

### ISSUE THREAD

**Issue by sebaiona** [StefH/PrimeNG-DataTable-Extensions#18]
Hi,

I'm currently using your extension and it works great (thanks by the way !).

I juste have one little problem due to the devDependencies out of date.
I use an `HttpInterceptor` which intercepts the http requests done by `HttpClient` (I think both were introduced in angular 4.3).

Given though PrimeNG-DataTable-Extensions have an old dependency to `Http` the interceptor doesn't work...

I just tried to copy the code in my solution and it works great (all the up-to-date dependencies doesn't create any error).

If you could just update the dependencies of the package, everything should work fine !

Thanks in advance !

**Comment by StefH** [comment]
Thanks for reporting.

I'll update dependencies for Angular to latest 4.x.x version. I'll also update primeng.

**Comment by sebaiona** [comment]
We're even in 5.0.5 now, and still no problem  ;)

Thanks in advance!!

**Comment by StefH** [comment]
NPM is updated, Please test.

**Comment by sebaiona** [comment]
I forgot to mention that angular-odata-es5 is out of date too...

When I do `applyLazyLoadEvent`, I have this error :
```
Argument of type 'ODataQuery<T>' is not assignable to parameter of type 'ODataQuery<T>'.
Types have separate declarations of a private property '_filter'.
```

I guess my ODataQuery is too recent for the function in the current state...
(it seems to be the only problem)

**Comment by StefH** [comment]
Sorry. I'll fix it again.

**Comment by sebaiona** [comment]
No problem. 
Let me know when it's done and I'll test as soon as I can ;)

**Comment by StefH** [comment]
please retest

**Comment by sebaiona** [comment]
Can you update it on npm please.

Given though what I saw, it should be ok !

**Comment by StefH** [comment]
npm version 0.0.4 uploaded

**Comment by sebaiona** [comment]
Thank you very much, everything is working fine !
